import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const configPath = path.join(root, 'data', 'readme-sources.json');
const outputDir = path.join(root, 'assets', 'readmes');
const token = process.env.GITHUB_TOKEN;
const apiHeaders = {
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'tian1224.github.io-readme-sync'
};

if (token) apiHeaders.Authorization = `Bearer ${token}`;

function escapeAttribute(value) {
    return String(value)
        .replaceAll('&', '&amp;')
        .replaceAll('"', '&quot;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;');
}

async function requestJson(url) {
    const response = await fetch(url, { headers: apiHeaders });
    if (!response.ok) {
        throw new Error(`${response.status} ${response.statusText} (${url})`);
    }
    return response.json();
}

async function renderMarkdown(markdown, context) {
    const response = await fetch('https://api.github.com/markdown', {
        method: 'POST',
        headers: { ...apiHeaders, 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: markdown, mode: 'gfm', context })
    });
    if (!response.ok) {
        throw new Error(`${response.status} ${response.statusText} (Markdown API)`);
    }
    return response.text();
}

function encodeRepositoryPath(value) {
    return value
        .split('/')
        .filter(Boolean)
        .map((part) => encodeURIComponent(part))
        .join('/');
}

function rewriteRelativeLinks(html, source, branch) {
    const repository = `${source.owner}/${source.repo}`;
    const rawBase = `https://raw.githubusercontent.com/${repository}/${encodeURIComponent(branch)}/`;
    const webBase = `https://github.com/${repository}/blob/${encodeURIComponent(branch)}/`;

    return html.replace(/\s(src|href)="([^"]+)"/g, (attribute, type, value) => {
        if (/^(?:[a-z][a-z\d+.-]*:|\/\/|#|\/)/i.test(value)) return attribute;

        const hashIndex = value.indexOf('#');
        const pathPart = hashIndex === -1 ? value : value.slice(0, hashIndex);
        const fragment = hashIndex === -1 ? '' : value.slice(hashIndex);
        const cleanPath = path.posix.normalize(pathPart.replace(/^\.\//, ''));
        const base = type === 'src' ? rawBase : webBase;
        return ` ${type}="${base}${encodeRepositoryPath(cleanPath)}${fragment}"`;
    });
}

async function syncReadme(source) {
    const repository = `${source.owner}/${source.repo}`;
    const repositoryInfo = await requestJson(`https://api.github.com/repos/${repository}`);
    const readme = await requestJson(`https://api.github.com/repos/${repository}/readme`);
    const markdown = Buffer.from(readme.content.replaceAll(/\s/g, ''), 'base64').toString('utf8');
    const rendered = rewriteRelativeLinks(
        await renderMarkdown(markdown, repository),
        source,
        repositoryInfo.default_branch
    );
    const output = [
        '<!-- Generated by scripts/sync-readmes.mjs. Do not edit this file directly. -->',
        `<div class="readme-content" data-readme-sha="${escapeAttribute(readme.sha)}">`,
        rendered.trim(),
        '</div>',
        ''
    ].join('\n');
    const outputPath = path.join(outputDir, `${source.slug}.html`);
    const current = await readFile(outputPath, 'utf8').catch(() => '');
    if (current !== output) await writeFile(outputPath, output, 'utf8');
    console.log(`${source.slug}: ${current === output ? 'unchanged' : 'updated'} (${readme.sha.slice(0, 7)})`);
}

const sources = JSON.parse(await readFile(configPath, 'utf8'));
await mkdir(outputDir, { recursive: true });

let failures = 0;
for (const source of sources) {
    try {
        await syncReadme(source);
    } catch (error) {
        failures += 1;
        console.error(`${source.slug}: ${error.message}`);
    }
}

if (failures > 0) process.exitCode = 1;
